python ../train.py \
  --data ../../data --train-size 5000 --valid-size 1000 \
  --ckpt-save-path ../../ckpts \
  --report-interval 50 \
  --nb-epochs 100 \
  --loss l2 \
  --noise-type gaussian \
  --noise-param 50 \
  --crop-size 128 \
  --plot-stats \
  --cuda