python3 ../train.py \
  --data ../../data --train-size 4200 --valid-size 800 \
  --ckpt-save-path ../../ckpts \
  --report-interval 50 \
  --nb-epochs 50 \
  --loss l2 \
  --noise-type gaussian \
  --noise-param 50 \
  --crop-size 64 \
  --plot-stats \
  --cuda
