python3 ../train.py \
  --train-dir ../../data/train --train-size 500 \
  --valid-dir ../../data/valid --valid-size 100 \
  --ckpt-save-path ../../ckpts \
  --report-interval 25 \
  --nb-epochs 10 \
  --loss l2 \
  --noise-type gaussian \
  --noise-param 50 \
  --crop-size 64 \
  --plot-stats \
  --cuda
